import { TTT, PosFix1, PosFix2, Classmates1, Signal1 } from "./assets/projects";
const projects = [
  {
    date: ["Sep 2021", "Present"],
    title: "Teaching Assistant - Machine Learning and Data Mining",
    type: "Part-Time - UBC Computer Science",
    skills: ["Python", "NumPy", "Machine Learning", "Teaching"],
    desc: [
      "Solidified understanding of core machine learning concepts by teaching them to other students",
      "Held weekly meetings to ensure students understand concepts taught in lecture (gradient descent, principal component analysis, neural networks)",
      "Graded assignments and exams to assess students level of understanding and gave relevant feedback",
    ],
    url: "https://github.com/UBC-CS/cpsc340-2021w1",
    images: [],
    video: [],
  },
  {
    date: ["Jan 2022"],
    title: "Spacestagram",
    type: "Personal Project",
    skills: ["React", "GitHub"],
    desc: [""],
    url: "https://github.com/UBC-CS/cpsc340-2021w1",
    images: [],
    video: [],
  },
  {
    date: ["Jan 2021", "Aug 2021"],
    title: "Machine Learning/Data Science Co-op",
    type: "Co-op - TTT Studios",
    skills: ["Python", "TensorFlow", "Dash", "AWS"],
    desc: [
      "Led the set up process of the AI services department",
      "Held client meetings as the lead AI engineer",
      "Designed and developed a Python based web application to visualize the progress of Covid-19 vaccinations around the world",
      "Deployed the website to AWS Elastic Beanstalk with continuous deployment and used AWS S3 to store data files",
      "Developed a PM analytics tool that increased project estimation accuracy by 60% using Monte Carlo simulations",
    ],
    url: "http://covid-19-vaccination.us-west-2.elasticbeanstalk.com/",
    images: [{ id: 0, src: TTT, alt: "Covid-19 Vaccination Dashboard" }],
    video: [],
  },
  {
    date: ["Mar 2021", "May 2021"],
    title: "Automatic Home Analysis",
    type: "Part-Time Work - KnockNow",
    skills: ["Python", "NLP"],
    desc: [
      "Identified key features in real estate listings using NLP",
      "Cleaned data by removing random spaces and fixing abbrheviations",
    ],
    url: "",
    images: [],
    video: [],
  },
  {
    date: ["Feb 2021"],
    title: "Signal Clone",
    type: "Personal Project - YouTube Tutorial",
    skills: ["React Native", "Expo", "Firebase"],
    desc: [
      "Created a Signal (chatting app) mobile app clone to gain familiarity with React Native and used Firebase for the authentication and the database",
    ],
    url: "https://github.com/Kojon74/Signal-Clone",
    images: [],
    video: [{ id: 0, src: Signal1, alt: "Video demo of Signal clone" }],
  },
  {
    date: ["Feb 2021"],
    title: "PosFix",
    type: "Hackathon - MakeUofT",
    skills: ["React Native", "Firebase", "Figma"],
    desc: [
      "Created a mobile application that keeps track and informs you of your posture based on sensor data",
      "Designed application with Figma, developed front-end with React Native and managed database with Firebase",
      "Collaborated remotely with teammates who developed hardware component",
      "Placed 5th in the 'Well Being' category",
    ],
    url: "https://devpost.com/software/posfix",
    images: [
      { id: 0, src: PosFix1, alt: "PosFix Homepage" },
      { id: 1, src: PosFix2, alt: "Hardware setup" },
    ],
    video: [],
  },
  {
    date: ["Feb 2021"],
    title: "Classmates",
    type: "Hackathon - CalgaryHacks 2021",
    skills: ["React", "Firebase", "Figma"],
    desc: [
      "Created a web application as a platform for classmates to talk to one another which can be difficult to do, especially during this pandemic",
      "Helped teammates gain familiarity with React by answering any questions they had",
      "Implemented the discussion style feature for this project, where users can post questions and answers powered by a React front-end and Firebase back-end",
    ],
    url: "https://devpost.com/software/classmates",
    images: [],
    video: [{ id: 0, src: Classmates1, alt: "Video demo of Classmates" }],
  },
  {
    date: ["Jan 2021"],
    title: "Tennis Match Prediction",
    type: "Co-op - TTT Studios",
    skills: [
      "Dash",
      "H2O Wave",
      "Streamlit",
      "Python",
      "TensorFlow",
      "Keras",
      "Neural Network",
    ],
    desc: [
      "Tested multiple platforms for building data science websites by creating a tennis match prediction web application",
      "Documented work since I am the first team member of the Data Science/Machine Learning Department",
      "Created a deep neural network to predict the outcome of a given match given a bunch of parameters (player details, tournament details, etc.)",
    ],
    url: "",
    images: [],
    video: [],
  },
  {
    date: ["Jan 2021"],
    title: "Right or Left",
    type: "Hackathon - Hack the Northeast",
    skills: [
      "React",
      "Chrome Extensions API",
      "Python",
      "Google Cloud AutoML Natural Language",
      "Flask",
    ],
    desc: [
      "Created a Chrome Extension that detects the bias in the article the user is reading and classifies it as politically left or right leaning with a confidence interval and suggested similar articles but with opposing political bias to the user so they can gain a more well rounded understanding of the topic",
      "Created the front-end using React and the Chrome Extensions API",
      "Created two API calls using Flask; to calculate the bias in the current article, and find similar relevant articles",
      "Trained the bias detection model on the Google Cloud AutoML Natural Language platform on a dataset we created (manually)",
    ],
    url: "https://devpost.com/software/right-or-left",
    images: [],
    video: [],
  },
  {
    date: ["Dec 2020", "Jan 2021"],
    title: "Day Trading Algorithm",
    type: "Personal Project",
    skills: ["Python", "Day Trading", "IB API"],
    desc: [
      "Developed a day trading algorithm",
      "Created my own back testing environment to test my algorithms and calculate profits",
      "Learned many day trading concepts including many indicators, leverage and margins, stop losses and risk assessment, etc",
    ],
    url: "",
    images: [],
    video: [],
  },
  {
    date: ["Nov 2020"],
    title: "Spam Detector",
    type: "Personal Project - Coursera Guided Project",
    skills: ["Flask", "Python", "AWS"],
    desc: [
      "Built a spam detector using natural language processing and launched it as a serverless API using AWS Elastic Beanstalk technology",
      "Used the Flask framework to create the API, basic machine learning methods to build the spam detector & AWS desktop management console to deploy the spam detector into the AWS cloud servers",
      "Learned more about how to switch between different versions of my web application and also, monitoring my AWS servers using Elastic Beanstalk Management Console",
    ],
    url: "",
    images: [],
    video: [],
  },
];

export default projects;
