import {
  TTT,
  PosFix1,
  PosFix2,
  Classmates1,
  Signal1,
  Clearo1,
  LeftOrRight1,
} from "./assets/projects";
const projects = [
  {
    date: ["Feb 2021", "Present"],
    title: "Clearo iOS App",
    type: "Personal Project",
    skills: ["React Native", "TypeScript", "Firebase", "Figma", "Expo"],
    desc: [
      "Learned through personal experience and customer validation that many users experiencing acne don’t understand what is causing them since there are so many factors to consider",
      "Developed a mobile application to help users track their skin condition and help determine potential triggers for their facial acne",
      "Developed the frontend with React Native and TypeScript, database management and authentication with Firebase, design with Figma, and deployed using Expo",
      "Published to the Apple App Store where the app currently has 226 downloads and a 5 star rating",
      "Journaled my progress through multiple blog entries on my",
    ],
    companyURL: "https://www.clearo-app.com",
    projectURL:
      "https://apps.apple.com/us/app/clearo/id1644641276?platform=iphone",
    images: [{ id: 0, src: Clearo1, alt: "Clearo on the App Store" }],
    pinned: true,
  },
  {
    date: ["May 2022", "Aug 2022"],
    title: "Foodo Android App",
    type: "Class Project",
    skills: ["Android", "Java", "Node.js", "Azure", "Jest", "CI/CD", "Figma"],
    desc: [
      "Created an Android mobile application to make keeping track of all the restaurants you want to visit and the process of looking up restaurant information more convenient for users",
      "Developed the front-end with Java, back-end with Node.js running on a VM in Azure",
      "Tested the front-end with Expresso, back-end with Jest to achieve over 90% coverage",
      "Developed CI/CD pipeline to run unit tests as well as automated Codacity tests on every PR",
      "Created UI design with Figma",
    ],
    githubURL: "https://github.com/FoodoCPEN321/foodo",
    images: [],
    video: "Y2L-tUp1BHA",
  },
  {
    date: ["Jan 2022", "Apr 2022"],
    title: "Park n' Go",
    type: "Class Project",
    skills: [
      "React Native",
      "Firebase",
      "Python",
      "Flask",
      "Computer Vision",
      "System Verilog",
      "AWS",
      "CI/CD",
      "De1-SoC",
    ],
    desc: [
      "Noticed that people often have trouble estimating how long they will be parked for, which either leads to over paying, or underpaying and having to worry about getting a ticket",
      "Created a solution which uses cameras at the entrance and exit of parkades to read license plates and charge users according to the exact amount of time they have parked for",
      "Created a prototype using a camera connected to a DE1-SoC, which runs automatic license plate recognition (ALPR) accelerated by hardware, updated a companion app indicating to the user how long they've been parked for",
      "Developed the client mobile application with React Native, database management with Firebase, back-end in Node.js which was hosted on an AWS server",
      "Achieved over 90% accuracy on the ALPR model",
      "Scored the highest in the class for achieving such high accuracy with the ALPR model on the DE1-SoC",
    ],
    githubURL: "https://github.com/Kojon74/Park-n-Go",
    images: [],
    video: "7CVmkKwqOxI",
  },
  {
    date: ["Sep 2021", "Apr 2022"],
    title: "Teaching Assistant - Machine Learning and Data Mining",
    type: "UBC Department of Computer Science",
    skills: ["Python", "Scikit-learn", "NumPy", "Machine Learning", "Teaching"],
    desc: [
      "Solidified understanding of core machine learning concepts by teaching them to other students",
      "Held weekly meetings to ensure students understand concepts taught in lecture (gradient descent, principal component analysis, neural networks)",
      "Graded assignments and exams to assess students level of understanding and gave relevant feedback",
      "Helped students debug their coding assignments",
    ],
    companyURL: "https://github.com/UBC-CS/cpsc340-2021w1",
    images: [],
  },
  {
    date: ["Jan 2022"],
    title: "Swop",
    type: "nwHacks",
    skills: [
      "React Native",
      "Node.js",
      "Firebase",
      "AWS",
      "Expo",
      "GitHub",
      "Figma",
    ],
    desc: [
      "Created a mobile application platform to buy and sell products with an emphasis on trading",
      "Developed the front-end in React Native, back-end with Node.js, database management with Firebase, VM on AWS, design with Figma, and published with Expo",
      "Submitted to nwHacks, but continued working on it and applied for entrepeneurship@UBC",
    ],
    images: [],
    video: "D-RqCoTL1eM",
    pinned: true,
  },
  {
    date: ["Jan 2022"],
    title: "Spacestagram",
    type: "Personal Project",
    skills: ["React", "GitHub"],
    desc: [
      "Created an Instagram like social network feed with daily posts on interesting science facts",
      "Developed the frontend using React, hosted on GitHub pages",
    ],
    projectURL: "https://kojon74.github.io/Shopify-Frontend/",
    githubURL: "https://github.com/Kojon74/Shopify-Frontend/tree/master",
    images: [],
  },
  {
    date: ["Jan 2021", "Aug 2021"],
    title: "Machine Learning/Data Science Co-op",
    type: "TTT Studios",
    skills: ["Python", "TensorFlow", "Dash", "AWS"],
    desc: [
      "Led the set up process of the AI services department",
      "Held client meetings as the lead AI engineer",
      "Designed and developed a Python based web application to visualize the progress of Covid-19 vaccinations around the world",
      "Deployed the website to AWS Elastic Beanstalk with continuous deployment and used AWS S3 to store data files",
      "Developed a PM analytics tool that increased project estimation accuracy by 60% using Monte Carlo simulations",
    ],
    projectURL: "http://covid-19-vaccination.us-west-2.elasticbeanstalk.com/",
    companyURL: "https://ttt.studio",
    images: [{ id: 0, src: TTT, alt: "Covid-19 Vaccination Dashboard" }],
    pinned: true,
  },
  {
    date: ["Mar 2021", "May 2021"],
    title: "Data Science Intern",
    type: "KnockNow",
    skills: ["Python", "NLP"],
    desc: [
      "Developed a topic model that tagged real estate descriptions with relevant information using LDA and NMF (NLP)",
      "Created an SQL database on AWS RDS storing all project data",
      "Identified key features in real estate listings using NLP",
      "Cleaned data by removing random spaces and fixing abbrheviations",
    ],
    companyURL: "https://knocknow.net",
    images: [],
  },
  {
    date: ["Feb 2021"],
    title: "Signal Clone",
    type: "Personal Project",
    skills: ["React Native", "Expo", "Firebase"],
    desc: [
      "Created a Signal (chatting app) mobile app clone to gain familiarity with React Native and used Firebase for the authentication and the database",
    ],
    githubURL: "https://github.com/Kojon74/Signal-Clone",
    images: [],
    video: "1gjKhoqMYbc",
  },
  {
    date: ["Feb 2021"],
    title: "PosFix",
    type: "MakeUofT Hackathon",
    skills: ["React Native", "Firebase", "Figma"],
    desc: [
      "Created a mobile application that keeps track and informs you of your posture based on sensor data",
      "Designed application with Figma, developed front-end with React Native and managed database with Firebase",
      "Collaborated remotely with teammates who developed hardware component",
      "Placed 5th in the 'Well Being' category",
    ],
    projectURL: "https://devpost.com/software/posfix",
    githubURL: "https://github.com/Kojon74/PosFix",
    images: [
      { id: 0, src: PosFix1, alt: "PosFix Homepage" },
      { id: 1, src: PosFix2, alt: "Hardware setup" },
    ],
    video: "M4SF_171kio",
    pinned: true,
  },
  {
    date: ["Feb 2021"],
    title: "Classmates",
    type: "CalgaryHacks 2021",
    skills: ["React", "Firebase", "Figma"],
    desc: [
      "Noticed that working together with fellow classmates can significantly improve your learning, however, it can be difficult to meet people in class especially during the pandemic",
      "Created a web application as a platform for students to interact with each other, and help understand problems they may have",
      "Implemented the discussion style feature for this project, where users can post questions and answers powered by a React front-end and Firebase back-end",
      "Taught my teammates React for this project, by helping them answer specific questions and delegating specific tasks to each person",
    ],
    projectURL: "https://devpost.com/software/classmates",
    githubURL: "https://github.com/Kojon74/Classmates",
    images: [],
    video: "_HXv9RRJF04",
  },
  {
    date: ["Jan 2021"],
    title: "Right or Left",
    type: "Hack the Northeast",
    skills: [
      "React",
      "Chrome Extensions API",
      "Python",
      "Google Cloud AutoML Natural Language",
      "Flask",
    ],
    desc: [
      "Created a Chrome Extension that detects the bias in the article the user is reading and classifies it as politically left or right leaning with a confidence interval and suggested similar articles but with opposing political bias to the user so they can gain a more well rounded understanding of the topic",
      "Created the front-end using React and the Chrome Extensions API",
      "Created two API calls using Flask; to calculate the bias in the current article, and find similar relevant articles",
      "Trained the bias detection model on the Google Cloud AutoML Natural Language platform on a dataset we created (manually)",
    ],
    projectURL: "https://devpost.com/software/right-or-left",
    githubURL: "https://github.com/cwen96/Right-or-Left",
    images: [{ id: 0, src: LeftOrRight1, alt: "Left or Right Demo" }],
    video: "c5SD3Z-D06A",
    pinned: true,
  },
  {
    date: ["Dec 2020", "Jan 2021"],
    title: "Day Trading Algorithm",
    type: "Personal Project",
    skills: ["Python", "Day Trading", "Interactive Broker API"],
    desc: [
      "Developed a program to read market trends and look for indicators to enter/exit the market",
      "Created my own back testing environment to test my algorithms and calculate profits on historical data",
      "Learned many day trading concepts including many indicators (exponential moving average, relative rtrength index, moving average convergence divergence, average true range), leverage and margins, stop losses and risk assessment, to name a few",
      "Realized this method would not work since to overcome the high trading fees on Interactive Broker I would need to invest more money than I had",
    ],
    images: [],
  },
  {
    date: ["Jun 2020", "Dec 2020"],
    title: "AI Research Intern",
    type: "Bosch",
    skills: ["Python", "TensorFlow", "Keras", "Machine Learning"],
    desc: [
      "Developed a skateboard video classification model using human pose detection and neural networks with Python, TensorFlow and Keras",
      "Experimented with stock market forecasting using RNN’s for time series data and NLP for sentimental analysis of relevant news articles",
      "Trained an AI agent to play complex mobile application games using reinforcement learning",
    ],
    companyURL: "https://www.bosch.ca",
    images: [],
    pinned: true,
  },
  {
    date: ["Nov 2020"],
    title: "Spam Detector",
    type: "Personal Project",
    skills: ["Python", "Flask", "Machine Learninng", "AWS"],
    desc: [
      "Built a spam detector using natural language processing and launched it as a serverless API using AWS Elastic Beanstalk technology",
      "Used the Flask framework to create the API, basic machine learning methods to build the spam detector & AWS desktop management console to deploy the spam detector into the AWS cloud servers",
      "Learned more about how to switch between different versions of my web application and also, monitoring my AWS servers using Elastic Beanstalk Management Console",
    ],
    githubURL: "https://github.com/Kojon74/SpamDetectorFlask",
    images: [],
  },
  {
    date: ["Jan 2020", "Apr 2020"],
    title: "Autonomous Robot",
    type: "Class Project",
    skills: ["Python", "Swift", "Firebase", "Raspberry Pi"],
    desc: [
      "Built a Raspberry Pi powered autonomous line following robot using reflective optical sensors",
      "Developed an iOS application in Swift to manually take control of the robot, used Firebase to communicate between the Raspberry Pi and the mobile app",
    ],
    githubURL: "",
    images: [],
    video: "yPFNwrm5XgQ",
  },
];

export default projects;
